import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NestedList from "@/pages/restaurant-list/index.page";

const inter = Inter({ subsets: ["latin"] });
const style = {
  backgroundColor: '#121111',
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{...style}} className={styles.description}>
          <NestedList />
        </div>
      </main>
    </>
  );
}
